export const GET_POSTS = 'GET_POSTS';

export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const AUTH_SUBMIT = 'AUTH_SUBMIT';
export const AUTH_VALIDATION = 'AUTH_VALIDATION';