export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const AUTH_SUBMIT = 'AUTH_SUBMIT';
export const AUTH_VALIDATION = 'AUTH_VALIDATION';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_CHANGE_FORM_VALID = 'AUTH_CHANGE_FORM_VALID';
export const AUTH_RESET_FORM = 'AUTH_RESET_FORM';