export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const AUTH_SUBMIT = 'AUTH_SUBMIT';
export const AUTH_VALIDATION = 'AUTH_VALIDATION';