export const FORGOT_PASSWORD_CHANGE_EMAIL = 'FORGOT_PASSWORD_CHANGE_EMAIL';
export const FORGOT_PASSWORD_VALIDATION = 'FORGOT_PASSWORD_VALIDATION';
export const FORGOT_PASSWORD_RESET_FORM = 'FORGOT_PASSWORD_RESET_FORM';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';