export const NEW_PASSWORD_CHANGE_PASSWORD = 'NEW_PASSWORD_CHANGE_PASSWORD';
export const NEW_PASSWORD_CHANGE_PASSWORD_REPEAT = 'NEW_PASSWORD_CHANGE_PASSWORD_REPEAT';
export const NEW_PASSWORD_CONFIRM_FAILURE = 'NEW_PASSWORD_CONFIRM_FAILURE';
export const NEW_PASSWORD_VALIDATION = 'NEW_PASSWORD_VALIDATION';
export const NEW_PASSWORD_RESET_FORM = 'NEW_PASSWORD_RESET_FORM';